name: empower_kids
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  audioplayers: ^3.0.1
  animated_splash_screen: ^1.3.0
  lottie: ^2.6.0
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2

flutter_icons:
  image_path_android: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: times
      fonts:
        - asset: fonts/times.ttf
